# Generated by Django 3.1 on 2020-08-23 10:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('nick_name', models.CharField(max_length=255, unique=True, verbose_name='닉네임')),
                ('phone', models.CharField(max_length=255, unique=True, verbose_name='전화번호')),
                ('date_of_birth', models.DateTimeField(unique=True, verbose_name='생년월일')),
                ('profile_ph', models.ImageField(unique=True, upload_to='', verbose_name='프로필사진')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 확인')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 확인')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
